% ==== Sweep Configuration ====
start_wavelength = 8;   % Start value in mm
end_wavelength   = 0.5;    % End value in mm
step_size        = -3;   % Negative for descending sweep

% ==== Generate Wavelength Vector ====
wavelengths = start_wavelength:step_size:end_wavelength;

% ==== Sweep Loop ====
for wl = wavelengths
    % Construct wavelength string and dynamic variable name
    wavelengthStr = sprintf('%d[mm]', wl);
    varname = sprintf('2025/Z_w%.1f', wl);           % Use 1 decimal place in varname
    
    % Display progress
    fprintf('Running for wavelength = %s -> varname = %s\n', wavelengthStr, varname);
    
    % Call the function with the current wavelength and dynamic variable name
    DesignSpaceStudy1D( ...
        varname, ...
        'ewfd.normE^2', ...
        0, ...
        5, ...
        'minmesh', 0.00005, ...
        'Ampl', 1e3, ...
        'maxmesh', 0.00005, ...
        'SimpStol', 5e-5, ...
        'I0', 0.005, ...
        'Iend', 0.925, ...
        'x0', 0.8, ...
        'xend', 1.2, ...
        'modelname', 'Scintillator2D_1DStudy_jRINDEXfreq', ...
        'Surf', [3, 10], ...
        'int', '2D', ...
        'wavelength', wavelengthStr, ...
        'parts', 8 ...
    );
    close all;
end
